version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        depends_on:
            - db

        environment:
            PMA_HOST: db

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
        - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        - ./wp-content/themes:/var/www/html/wp-content/themes
        - ./wp-content/plugins:/var/www/html/wp-content/plugins
        - ./wp-content/uploads:/var/www/html/wp-content/uploads
        - ./magazine-archive:/var/www/html/magazine-archive


volumes:
  db_data:
